### ISSUE TITLE
Resend 2, part 2: Revengeance

### ISSUE THREAD

**Issue by biblicabeebli** [onnela-lab/beiwe-backend#413]
### What works as of posting:
- There do not appear to be logic bugs with the scheduling of when a notification should be sent out.
    - _Thank gwad._
    - We fixed an issue that only occurred on production where.... it was a database-too-big problem...

### Current state:
- It can get too spammy, and it is repetitious.

### After deploying resend we encountered some issues with the fundamentals:
- We still have off-by-6-minutes bugs
    - but they are less common.
    - this is probably because my fix ends up depending on server load
    - this compounds the other too issues
- Participants can receive out-of-order notifications
    - This oversight occurred because the very high complexity was on ensuring stability, correctness, and app components of the updates.
    - Fortunately this is all now backend work, and the App work was solidly architected so we can handle this on the backend.
    - This occurs when a participant deletes notifications they receive (or whatever other acts that fully discard the notification)
- The notifications can get shifted in time when the period is not divisible by 24 hours.
    - This detail was overlooked in the interface on the website.
    - A repetition interval of 5 hours starting at midnight hits...:
        - midnight, 5am, 10am, 3pm, 8pm., but then hits 1am instead of midnight etc.
        - this means the notification for an old survey that is probably best considered to be "missed" keeps getting sent.
        - reporting of the wrong survey notification uuid is present.

---

### When sending ANY notification to the device, include all not-confirmed-received push notifications
- this solves all overlap issues and out of sync issues.
    - when multiple notifications are received all at the same time they are correctly "coalesced" inside the app.
       - todo: check whether the app adds all notification ids to all surveys that are visible due to all those notification\_s\_, or if notification uuids are attached to the target surveys individually.
- can we do this in keep-alive notifications? Dunno yet.

Work live on the relevant branch/server at the moment:
- send all uuids on any notification is currently implementd, has tests for logical correctness like other components of Resend, and is on our staging server.

---

### Other 
- oh cwap we don't have a full historical uuid mapping to original survey time/true-schedule for the associated api for @MMel099  (that isn't built yet).
    - this data might be preserved when the study marked as finished - need to check.
    - this data is not preserved when the schedules are edited and deleted-then-recreated.
- Notification info on the participant page used to be in the participant's time zone
    - this needs to be revisited, ideally we can display it like that historically, but we don't currently have timezone tracking
    - is there a database option that would allow this? that would besuper helpful....

### Remaining and Stretch Goals
- integrate the manual button with the push notification resend and tracking feature
- allow push notification of a survey that has never been sent to the participant instead of just a historical survey.
- tracking

Todo - complication:
- ArchivedEvents at the same historic scheduled time may block survey schedules of another type of survey(?) from being resent
- confirm if w have this problem it does not occur in resend logic itself.
- double check the ScheduledEvent creation logic, ensure we have a test that covers _resend_ behavior, not just push notification behavior.

**Comment by hydawo** [comment]
@MMel099 @jprince127 @QianJingyun 

Can you please provide your testing feedback? As a reminder here are the testing notes from our RA agenda meeting:

1. **Survey configuration - 3 hour resend logic**
    1. **Diary - daily at 9AM and 3PM**
        1. Daily Diary Day 1 Survey 1 - 9AM - 12PM Resend - 3PM Resend
        2. Daily Diary Day 1 Survey 2 - 3PM - 6PM Resend - 9PM Resend - 12AM Resend - 3AM Resend - 6AM Resend
        3. Daily Diary Day 2 Survey 1 - 9AM…
    2. **Tests**
        1. Does resend of Daily Survey 1 stop when Daily Survey 2 deploys?
        2. How many notifications are visible shortly after 12PM and 3PM?
            1. We believe this should be 2 total notifications
                1. Take screenshots
            2. Do not touch these notification at all, let them come in and pile up
        3. How many notifications are visible shortly after 6PM?
            1. We believe this should be 4 total notifications
                1. Take screenshots
            2. Click ANY notification, take surveys, check backend to confirm that all pending surveys were received (specifically Daily Survey 1)
    3. **User Testing Protocol**
        1. Enroll with new ID, set enrollment date to 3 days prior, wait for ~15 min
            1. Log number of surveys pending
            2. Take surveys
            3. Confirm all are marked as received on push history notification page
        2. Each day of testing
            1. Allow Daily Survey 1 to be sent at 9AM, resent at 12PM and resent at 3PM; do not interact with or clear these notifications
                1. Count/screenshot notifications at 9AM, 12PM, and 3PM
            2. Allow Daily Survey 2 to be sent at 3PM
                1. Count/screenshot notifications at 3PM
                2. Click ANY notification, take surveys, check backend to confirm that all pending surveys were received (specifically Daily Survey 1)

**Comment by QianJingyun** [comment]
Response to test:
a. I cannot tell which survey it is on the notification page. Checking the backend, I received Diary (this is Survey 1 I assume) at 3 PM after I received Grandfather Passage (Survey 2) at 12 AM. So, resend of Daily Survey 1 do not stop when Daily Survey 2 deploys.
b. Shortly after 12PM, I can see 2 notifications. Shortly after 3 PM, I can see 3 notifications.
<details>
  <summary>Click to toggle image</summary>
  <img src="https://your-image-url.com/image.png" alt="Description" width="500">
</details>
c. I didn't get further notification after 6PM. So there are 3 notifications. Checking the backend, pending surveys were received.

**Comment by hydawo** [comment]
Jenny ([y1ihn2t7](https://staging.beiwe.org/view_study/100/participant/y1ihn2t7)) at 3PM on 2/13/25
- At 3PM, had 3 total notifications (1 for Diary 1 at 9AM, 1 for Diary 1 Resend at 12PM, 1 for Diary 2 at 3PM)
- At 3:12PM, additional resend for both Diary 1 and Diary 2 erroneously occurred
- Jenny clicked on 3:12PM notification

[] Check iOS log to see which UUID(s) are logged for "open survey" event ~3:14PM

![Image](https://github.com/user-attachments/assets/e2254b4b-334b-4091-93a8-2093b910b197)

**Comment by biblicabeebli** [comment]
Updates
- The v1 fix has been pushed to production.  It was a strict improvement that solved many issues.
- A possible fix for off-by-6-minutes bugs has been deployed to staging.

**Comment by biblicabeebli** [comment]
updates:
- the staging server is running ~v3 of the fixes
- I believe survey notifications are all now bundling and getting their timers reset correctly now.

The reason this got so messy is that the off-by-6-minute bug was interacting with the bundling code, causing some really unexpected and unpredictable behavior.

(But I think we are done with the server side of this stuff.)

**Comment by hydawo** [comment]
Hi @biblicabeebli posting some results from testing both 1) recognition of bundled notifications as resends and 2) 6-Minute-Bug

**TLDR:**
- Bundle recognition is working → this resolves the erroneous notifications that were spawning from a schedule affected by 6-Minute-Bug
- 6-Minute-Bug still seems to occur at random
- The next initial send of the next survey brings all pending resends for prior unconfirmed surveys back in line (if they were affected by 6-Minute-Bug

![Image](https://github.com/user-attachments/assets/31a59036-28d9-456b-8fe0-8d43560b11a5)

**Comment by biblicabeebli** [comment]
@hydawo's post and screenshots have been reviewed

The timer for the study had previously been intentionally set to 181 minutes, at sometime after 11pm on the 26th it was reset to 180 minutes, the page now looks like this:

<img width=50% src=https://github.com/user-attachments/assets/f6de268c-1ace-40ee-94a7-888a580d0393>

This was mostly a human oversight, but it does raise the question of whether we should be handling the case where the timer is not evenly divisible by 6 minutes.

However, resolving this particular edge case so that it would trigger at the start of the 6-minute period in which it would trigger is not even obviously correct, and the amount of effort to then extend testing of this feature is high.

In addition, I'm not convinced that the current solution with global resend timers is actually particularly good.  So, I will simply state that we are at a feature freeze here and will push this to production as soon as real world testing allows.

**Comment by hydawo** [comment]
Hi @biblicabeebli ,

More data from from [Yale Beta Study 2.0](https://staging.beiwe.org/view_study/100) - [qb6gfgot](https://staging.beiwe.org/view_study/100/participant/qb6gfgot)

- Bundle recognition is working (as before)
- 6m bug seems to be resolved (note all send times are flat on the hour)

![Image](https://github.com/user-attachments/assets/2d6455bd-f628-4160-ac87-e5315529ea6f)

Do you think we are ready to push this bundle recognition/6m bug fix to production?

CC: @MMel099

**Comment by biblicabeebli** [comment]
Yeah I think we can and should push.
There's a bit of a bundle of updates here so I will get them ready.

**Comment by biblicabeebli** [comment]
updates are bundled up and have been collectively pushed to staging server for some basic testing, doing some cleanup and quality of life improvements before pushing to production servers.

**Comment by biblicabeebli** [comment]
This thread is now locked. If a new issue of new tasks is to be worked on a new issue should be opened referencing this issue.
Development of this feature is currently paused as we rethink the best mechanism to ensure participants on the notification-dependent platform (iOS) receive their notifications as consistently and in as timely a fashion as possible, without overwhelming users.
